### ISSUE TITLE
Extending MockFactory doesn't compile on 6.0.0

### ISSUE THREAD

**Issue by evis** [paulbutcher/ScalaMock#543]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)

6.0.0

### Scala Version (e.g. 2.12)

3.3.4

### Runtime (JVM or JS)

JVM

### Reproducible Test Case

https://scastie.scala-lang.org/KrVlHBKyS3aL06nlSAkO3g

```scala
import org.scalamock.scalatest.MockFactory

trait Test extends MockFactory
```

I have such traits to avoid code duplication (actually, mocks are initialized there).

### Please describe the expected behavior of the issue

The code should compile successfully, as it did with ScalaMock version 5.2.0.

### Please provide a description of what actually happens

The code does not compile, producing the following error:

```
illegal inheritance: self type Playground.Test of trait Test does not conform to self type org.scalatest.TestSuite
of parent trait MockFactory
```

When I modify the trait as follows, it compiles:

```scala
trait Test extends MockFactory with TestSuite {
  abstract override def withFixture(test: NoArgTest): Outcome = super.withFixture(test)
}
```

However, this approach introduces unnecessary boilerplate code.

Questions:
- Is there an alternative way to structure the code to avoid the compilation error without adding boilerplate?
- Is this behavior expected with the current version of ScalaMock?

**Comment by goshacodes** [comment]
Hi, this one compiles just fine.
MockFactory itself should be mixed only with something extending TestSuite

```scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.TestSuite

trait Test extends MockFactory { this: TestSuite => }

println("OK")
```
https://scastie.scala-lang.org/Zz0PrnosQfSeTQK6Vf68Xg

**Comment by evis** [comment]
Thanks for the suggestion! Sorry for bothering you, I should've figured it out myself...
