### ISSUE TITLE
Compilation error using MockFactory with ScalaTest 2.0.M6-SNAP21

### ISSUE THREAD

**Issue by fernandoracca** [paulbutcher/ScalaMock#45]
I've tried the preview release of ScalaTest and it breaks in the withFixture method.

[error] D:\app\ACalculatorTest.scala:10: overriding method
thFixture in trait Suite of type (test: ACalculatorTest.this.NoArgTest)org.scalatest.Outcome;
[error]  method withFixture in trait MockFactory of type (test: ACalculatorTest.this.NoArgTest)Unit has incompatible type
[error] class ACalculatorTest extends FunSpec with MockFactory with TieringFixture {
[error]       ^

class ACalculatorTest extends FunSpec with MockFactory { 

 val aMock = mockFunction[JDouble, JDouble]
... } 

This code compiles with 2.0.M5
